#!/usr/bin/env bash

git add -A | true
git commit -m "Preparing to publish from master" | true

gitbook build

git add -A | true
git commit -m "GitBook built master" | true

git push origin master:master
git fetch origin gh-pages
git checkout --track -b gh-pages origin/gh-pages  | git checkout gh-pages

rm -rf ../guide/.git/../*  # The up/down is to make sure the rm is in the right context
git checkout master -- _book
mv _book/* .
rmdir _book

git add -A
git commit -m "Publishing."
git push origin gh-pages:gh-pages
git checkout master

echo done!
